export const radicals=[
  {	character:"一",	pinyin:"yī",	definition:"one",	variants:[],	traditional:"",},
  {	character:"丨",	pinyin:"gǔn",	definition:"line",	variants:[],	traditional:"",},
  {	character:"丶",	pinyin:"zhǔ",	definition:"dot",	variants:[],	traditional:"",},
  {	character:"丿",	pinyin:"piě",	definition:"slash",	variants:["㇏","乀"],	traditional:"",},
  {	character:"乙",	pinyin:"yǐ",	definition:"second",	variants:["乚","乛","⺄"],	traditional:"",},
  {	character:"亅",	pinyin:"jué",	definition:"hook",	variants:[],	traditional:"",},
  {	character:"二",	pinyin:"èr",	definition:"two",	variants:[],	traditional:"",},
  {	character:"亠",	pinyin:"tóu",	definition:"lid",	variants:[],	traditional:"",},
  {	character:"人",	pinyin:"rén",	definition:"man",	variants:["亻","𠆢"],	traditional:"",}, // 𠆢
  {	character:"儿",	pinyin:"ér",	definition:"son, legs",	variants:[],	traditional:"",},
  {	character:"入",	pinyin:"rù",	definition:"enter",	variants:[],	traditional:"",},
  {	character:"八",	pinyin:"bā",	definition:"eight",	variants:["丷"],	traditional:"",},
  {	character:"冂",	pinyin:"jiōng",	definition:"down box",	variants:[],	traditional:"",},
  {	character:"冖",	pinyin:"mì",	definition:"cover",	variants:[],	traditional:"",},
  {	character:"冫",	pinyin:"bīng",	definition:"ice",	variants:[],	traditional:"",},
  {	character:"几",	pinyin:"jī",	definition:"table",	variants:[],	traditional:"",},
  {	character:"凵",	pinyin:"qū",	definition:"open box",	variants:[],	traditional:"",},
  {	character:"刀",	pinyin:"dāo",	definition:"knife",	variants:["刂","⺈"],	traditional:"",},
  {	character:"力",	pinyin:"lì",	definition:"power",	variants:[],	traditional:"",},
  {	character:"勹",	pinyin:"bāo",	definition:"wrap",	variants:[],	traditional:"",},
  {	character:"匕",	pinyin:"bǐ",	definition:"spoon",	variants:[],	traditional:"",},
  {	character:"匚",	pinyin:"fāng",	definition:"right open box",	variants:[],	traditional:"",},
  {	character:"匸",	pinyin:"xǐ",	definition:"hiding enclosure",	variants:[],	traditional:"",},
  {	character:"十",	pinyin:"shí",	definition:"ten",	variants:[],	traditional:"",},
  {	character:"卜",	pinyin:"bǔ",	definition:"divination",	variants:[],	traditional:"",},
  {	character:"卩",	pinyin:"jié",	definition:"seal",	variants:[],	traditional:"",},
  {	character:"厂",	pinyin:"hàn",	definition:"cliff",	variants:[],	traditional:"",},
  {	character:"厶",	pinyin:"sī",	definition:"private",	variants:[],	traditional:"",},
  {	character:"又",	pinyin:"yòu",	definition:"again",	variants:[],	traditional:"",},
  {	character:"口",	pinyin:"kǒu",	definition:"mouth",	variants:[],	traditional:"",},
  {	character:"囗",	pinyin:"wéi",	definition:"enclosure",	variants:[],	traditional:"",},
  {	character:"土",	pinyin:"tǔ",	definition:"earth",	variants:[],	traditional:"",},
  {	character:"士",	pinyin:"shì",	definition:"scholar",	variants:[],	traditional:"",},
  {	character:"夂",	pinyin:"zhǐ",	definition:"go",	variants:[],	traditional:"",},
  {	character:"夊",	pinyin:"suī",	definition:"go slowly",	variants:[],	traditional:"",},
  {	character:"夕",	pinyin:"xī",	definition:"evening",	variants:[],	traditional:"",},
  {	character:"大",	pinyin:"dà",	definition:"big",	variants:[],	traditional:"",},
  {	character:"女",	pinyin:"nǚ",	definition:"woman",	variants:[],	traditional:"",},
  {	character:"子",	pinyin:"zǐ",	definition:"child",	variants:[],	traditional:"",},
  {	character:"宀",	pinyin:"mián",	definition:"roof",	variants:[],	traditional:"",},
  {	character:"寸",	pinyin:"cùn",	definition:"inch",	variants:[],	traditional:"",},
  {	character:"小",	pinyin:"xiǎo",	definition:"small",	variants:["⺌","⺍","𭕄"],	traditional:"",}, // 𭕄 (!= ⺍)
  {	character:"尢",	pinyin:"wāng",	definition:"lame",	variants:["兀","尣"],	traditional:"",}, // 尣
  {	character:"尸",	pinyin:"shī",	definition:"corpse",	variants:[],	traditional:"",},
  {	character:"屮",	pinyin:"chè",	definition:"sprout",	variants:[],	traditional:"",},
  {	character:"山",	pinyin:"shān",	definition:"mountain",	variants:[],	traditional:"",},
  {	character:"川",	pinyin:"chuān",	definition:"river",	variants:["𡿨","巜","巛"],	traditional:"",}, // 𡿨
  {	character:"工",	pinyin:"gōng",	definition:"work",	variants:[],	traditional:"",},
  {	character:"己",	pinyin:"jǐ",	definition:"oneself",	variants:[],	traditional:"",},
  {	character:"巾",	pinyin:"jīn",	definition:"towel",	variants:[],	traditional:"",},
  {	character:"干",	pinyin:"gān",	definition:"dry",	variants:[],	traditional:"",},
  {	character:"幺",	pinyin:"yāo",	definition:"short thread",	variants:["么"],	traditional:"",},
  {	character:"广",	pinyin:"guǎng",	definition:"shelter",	variants:[],	traditional:"",},
  {	character:"廴",	pinyin:"yǐn",	definition:"stride",	variants:[],	traditional:"",},
  {	character:"廾",	pinyin:"gǒng",	definition:"two hands",	variants:[],	traditional:"",},
  {	character:"弋",	pinyin:"yì",	definition:"shoot",	variants:[],	traditional:"",},
  {	character:"弓",	pinyin:"gōng",	definition:"bow",	variants:[],	traditional:"",},
  {	character:"彐",	pinyin:"jì",	definition:"snout",	variants:["彑","⺕"],	traditional:"",}, // ⺕
  {	character:"彡",	pinyin:"shān",	definition:"bristle",	variants:[],	traditional:"",},
  {	character:"彳",	pinyin:"chì",	definition:"step",	variants:[],	traditional:"",},
  {	character:"心",	pinyin:"xīn",	definition:"heart",	variants:["忄","㣺","⺗"],	traditional:"",}, // 㣺 (!= ⺗)
  {	character:"戈",	pinyin:"gē",	definition:"halberd",	variants:[],	traditional:"",},
  {	character:"户",	pinyin:"hù",	definition:"door",	variants:["戶","戸"],	traditional:"",}, // 戶, 戸
  {	character:"手",	pinyin:"shǒu",	definition:"hand",	variants:["扌","龵"],	traditional:"",},
  {	character:"支",	pinyin:"zhī",	definition:"branch",	variants:[],	traditional:"",},
  {	character:"攴",	pinyin:"pū",	definition:"rap",	variants:["攵"],	traditional:"",},
  {	character:"文",	pinyin:"wén",	definition:"script",	variants:[],	traditional:"",},
  {	character:"斗",	pinyin:"dǒu",	definition:"dipper",	variants:[],	traditional:"",},
  {	character:"斤",	pinyin:"jīn",	definition:"axe",	variants:[],	traditional:"",},
  {	character:"方",	pinyin:"fāng",	definition:"square",	variants:[],	traditional:"",},
  {	character:"无",	pinyin:"wú",	definition:"not",	variants:["旡"],	traditional:"",},
  {	character:"日",	pinyin:"rì",	definition:"sun",	variants:[],	traditional:"",},
  {	character:"曰",	pinyin:"yuē",	definition:"say",	variants:[],	traditional:"",},
  {	character:"月",	pinyin:"yuè",	definition:"moon",	variants:[],	traditional:"",},
  {	character:"木",	pinyin:"mù",	definition:"tree",	variants:[],	traditional:"",},
  {	character:"欠",	pinyin:"qiàn",	definition:"lack",	variants:[],	traditional:"",},
  {	character:"止",	pinyin:"zhǐ",	definition:"stop",	variants:[],	traditional:"",},
  {	character:"歹",	pinyin:"dǎi",	definition:"death",	variants:["歺"],	traditional:"",},
  {	character:"殳",	pinyin:"shū",	definition:"weapon",	variants:[],	traditional:"",},
  {	character:"毋",	pinyin:"wú",	definition:"mother",	variants:["母"],	traditional:"",}, // 毋
  {	character:"比",	pinyin:"bǐ",	definition:"compare",	variants:[],	traditional:"",},
  {	character:"毛",	pinyin:"máo",	definition:"fur",	variants:[],	traditional:"",},
  {	character:"氏",	pinyin:"shì",	definition:"clan",	variants:[],	traditional:"",},
  {	character:"气",	pinyin:"qì",	definition:"steam",	variants:[],	traditional:"",},
  {	character:"水",	pinyin:"shuǐ",	definition:"water",	variants:["氵","氺"],	traditional:"",},
  {	character:"火",	pinyin:"huǒ",	definition:"fire",	variants:["灬"],	traditional:"",},
  {	character:"爪",	pinyin:"zhǎo",	definition:"claw",	variants:["爫","⺤",],	traditional:"",}, // ⺤, ⺥
  {	character:"父",	pinyin:"fù",	definition:"father",	variants:[],	traditional:"",},
  {	character:"爻",	pinyin:"yáo",	definition:"double x",	variants:[],	traditional:"",},
  {	character:"爿",	pinyin:"qiáng",	definition:"half tree trunk",	variants:["丬"],	traditional:"",},
  {	character:"片",	pinyin:"piàn",	definition:"slice",	variants:[],	traditional:"",},
  {	character:"牙",	pinyin:"yá",	definition:"fang",	variants:[],	traditional:"",},
  {	character:"牛",	pinyin:"niú",	definition:"cow",	variants:["牜","⺧", "𠂒"],	traditional:"",},
  {	character:"犬",	pinyin:"quǎn",	definition:"dog",	variants:["犭"],	traditional:"",},
  {	character:"玄",	pinyin:"xuán",	definition:"profound",	variants:[],	traditional:"",},
  {	character:"玉",	pinyin:"yù",	definition:"jade",	variants:["王","玊","⺩"],	traditional:"",},
  {	character:"瓜",	pinyin:"guā",	definition:"melon",	variants:[],	traditional:"",},
  {	character:"瓦",	pinyin:"wǎ",	definition:"tile",	variants:[],	traditional:"",},
  {	character:"甘",	pinyin:"gān",	definition:"sweet",	variants:[],	traditional:"",},
  {	character:"生",	pinyin:"shēng",	definition:"life",	variants:[],	traditional:"",},
  {	character:"用",	pinyin:"yòng",	definition:"use",	variants:[],	traditional:"",},
  {	character:"田",	pinyin:"tián",	definition:"field",	variants:[],	traditional:"",},
  {	character:"疋",	pinyin:"pǐ",	definition:"cloth",	variants:["𤴓","𤴔"],	traditional:"",},
  {	character:"疒",	pinyin:"nè",	definition:"sickness",	variants:[],	traditional:"",},
  {	character:"癶",	pinyin:"bō",	definition:"steps",	variants:[],	traditional:"",},
  {	character:"白",	pinyin:"bái",	definition:"white",	variants:[],	traditional:"",},
  {	character:"皮",	pinyin:"pí",	definition:"skin",	variants:[],	traditional:"",},
  {	character:"皿",	pinyin:"mǐn",	definition:"dish",	variants:[],	traditional:"",},
  {	character:"目",	pinyin:"mù",	definition:"eye",	variants:["⺫"],	traditional:"",},
  {	character:"矛",	pinyin:"máo",	definition:"spear",	variants:[],	traditional:"",},
  {	character:"矢",	pinyin:"shǐ",	definition:"arrow",	variants:[],	traditional:"",},
  {	character:"石",	pinyin:"shí",	definition:"stone",	variants:[],	traditional:"",},
  {	character:"示",	pinyin:"shì",	definition:"spirit",	variants:["礻"],	traditional:"",},
  {	character:"禸",	pinyin:"róu",	definition:"track",	variants:[],	traditional:"",},
  {	character:"禾",	pinyin:"hé",	definition:"grain",	variants:[],	traditional:"",},
  {	character:"穴",	pinyin:"xué",	definition:"cave",	variants:[],	traditional:"",},
  {	character:"立",	pinyin:"lì",	definition:"stand",	variants:[],	traditional:"",},
  {	character:"竹",	pinyin:"zhú",	definition:"bamboo",	variants:["𥫗", "⺮"],	traditional:"",}, // 𥫗 (!= ⺮)
  {	character:"米",	pinyin:"mǐ",	definition:"rice",	variants:[],	traditional:"",},
  {	character:"糸",	pinyin:"mì",	definition:"silk",	variants:["纟"],	traditional:"糹",},
  {	character:"缶",	pinyin:"fǒu",	definition:"jar",	variants:[],	traditional:"",},
  {	character:"网",	pinyin:"wǎng",	definition:"net",	variants:["⺳","罓","罒"],	traditional:"",},
  {	character:"羊",	pinyin:"yáng",	definition:"sheep",	variants:["⺶","𦍌"],	traditional:"",}, // 𦍌
  {	character:"羽",	pinyin:"yǔ",	definition:"feather",	variants:[],	traditional:"",},
  {	character:"老",	pinyin:"lǎo",	definition:"old",	variants:["耂"],	traditional:"",},
  {	character:"而",	pinyin:"ér",	definition:"and",	variants:[],	traditional:"",},
  {	character:"耒",	pinyin:"lěi",	definition:"plow",	variants:[],	traditional:"",},
  {	character:"耳",	pinyin:"ěr",	definition:"ear",	variants:[],	traditional:"",},
  {	character:"聿",	pinyin:"yù",	definition:"brush",	variants:["⺻","肀"],	traditional:"",},
  {	character:"肉",	pinyin:"ròu",	definition:"meat",	variants:["⺼"],	traditional:"",},
  {	character:"臣",	pinyin:"chén",	definition:"minister",	variants:[],	traditional:"",},
  {	character:"自",	pinyin:"zì",	definition:"self",	variants:[],	traditional:"",},
  {	character:"至",	pinyin:"zhì",	definition:"arrive",	variants:[],	traditional:"",},
  {	character:"臼",	pinyin:"jiù",	definition:"mortar",	variants:[],	traditional:"",},
  {	character:"舌",	pinyin:"shé",	definition:"tongue",	variants:[],	traditional:"",},
  {	character:"舛",	pinyin:"chuǎn",	definition:"oppose",	variants:[],	traditional:"",},
  {	character:"舟",	pinyin:"zhōu",	definition:"boat",	variants:[],	traditional:"",},
  {	character:"艮",	pinyin:"gēn",	definition:"stopping",	variants:[],	traditional:"",},
  {	character:"色",	pinyin:"sè",	definition:"color",	variants:[],	traditional:"",},
  {	character:"艸",	pinyin:"cǎo",	definition:"grass",	variants:["艹","䒑"],	traditional:"",}, // ⺿, 䒑
  {	character:"虍",	pinyin:"hū",	definition:"tiger",	variants:[],	traditional:"",},
  {	character:"虫",	pinyin:"huǐ",	definition:"insect",	variants:[],	traditional:"",},
  {	character:"血",	pinyin:"xuè",	definition:"blood",	variants:[],	traditional:"",},
  {	character:"行",	pinyin:"xíng",	definition:"intersection",	variants:[],	traditional:"",},
  {	character:"衣",	pinyin:"yī",	definition:"clothes",	variants:["衤","𧘇"],	traditional:"",}, // 𧘇
  {	character:"西",	pinyin:"xī",	definition:"west",	variants:["覀"],	traditional:"",}, // 襾
  {	character:"见",	pinyin:"jiàn",	definition:"see",	variants:[],	traditional:"見",},
  {	character:"角",	pinyin:"jiǎo",	definition:"horn",	variants:[],	traditional:"",}, // ⻇
  {	character:"言",	pinyin:"yán",	definition:"speech",	variants:["讠"],	traditional:"訁",},
  {	character:"谷",	pinyin:"gǔ",	definition:"valley",	variants:[],	traditional:"",},
  {	character:"豆",	pinyin:"dòu",	definition:"bean",	variants:[],	traditional:"",},
  {	character:"豕",	pinyin:"shǐ",	definition:"pig",	variants:[],	traditional:"",},
  {	character:"豸",	pinyin:"zhì",	definition:"badger",	variants:[],	traditional:"",},
  {	character:"贝",	pinyin:"bèi",	definition:"shell",	variants:[],	traditional:"貝",},
  {	character:"赤",	pinyin:"chì",	definition:"red",	variants:[],	traditional:"",},
  {	character:"走",	pinyin:"zǒu",	definition:"run",	variants:[],	traditional:"",},
  {	character:"足",	pinyin:"zú",	definition:"foot",	variants:["𧾷"],	traditional:"",},
  {	character:"身",	pinyin:"shēn",	definition:"body",	variants:[],	traditional:"",},
  {	character:"车",	pinyin:"chē",	definition:"cart",	variants:[],	traditional:"車",},
  {	character:"辛",	pinyin:"xīn",	definition:"bitter",	variants:[],	traditional:"",},
  {	character:"辰",	pinyin:"chén",	definition:"morning",	variants:[],	traditional:"",},
  {	character:"辵",	pinyin:"chuò",	definition:"walk",	variants:["辶"],	traditional:"",}, // ⻌, ⻍, ⻎
  {	character:"邑",	pinyin:"yì",	definition:"city",	variants:["阝"],	traditional:"",},
  {	character:"酉",	pinyin:"yǒu",	definition:"wine",	variants:[],	traditional:"",},
  {	character:"釆",	pinyin:"biàn",	definition:"distinguish",	variants:[],	traditional:"",},
  {	character:"里",	pinyin:"lǐ",	definition:"village",	variants:[],	traditional:"",},
  {	character:"金",	pinyin:"jīn",	definition:"gold",	variants:["钅"],	traditional:"釒",},
  {	character:"长",	pinyin:"cháng",	definition:"long",	variants:["镸"],	traditional:"長",},
  {	character:"门",	pinyin:"mén",	definition:"gate",	variants:[],	traditional:"門",},
  {	character:"阜",	pinyin:"fù",	definition:"mound",	variants:["阝"],	traditional:"",},
  {	character:"隶",	pinyin:"lì",	definition:"slave",	variants:[],	traditional:"",},
  {	character:"隹",	pinyin:"zhuī",	definition:"short-tailed bird",	variants:[],	traditional:"",},
  {	character:"雨",	pinyin:"yǔ",	definition:"rain",	variants:[],	traditional:"",},
  {	character:"青",	pinyin:"qīng",	definition:"blue",	variants:[],	traditional:"靑",},
  {	character:"非",	pinyin:"fēi",	definition:"wrong",	variants:[],	traditional:"",},
  {	character:"面",	pinyin:"miàn",	definition:"face",	variants:[],	traditional:"靣",},
  {	character:"革",	pinyin:"gé",	definition:"leather",	variants:[],	traditional:"",},
  {	character:"韦",	pinyin:"wéi",	definition:"tanned leather",	variants:[],	traditional:"韋",},
  {	character:"韭",	pinyin:"jiǔ",	definition:"leek",	variants:[],	traditional:"",},
  {	character:"音",	pinyin:"yīn",	definition:"sound",	variants:[],	traditional:"",},
  {	character:"页",	pinyin:"yè",	definition:"page",	variants:[],	traditional:"頁",},
  {	character:"风",	pinyin:"fēng",	definition:"wind",	variants:[],	traditional:"風",},
  {	character:"飞",	pinyin:"fēi",	definition:"fly",	variants:[],	traditional:"飛",},
  {	character:"食",	pinyin:"shí",	definition:"eat",	variants:["饣"],	traditional:"飠",},
  {	character:"首",	pinyin:"shǒu",	definition:"head",	variants:[],	traditional:"",},
  {	character:"香",	pinyin:"xiāng",	definition:"fragrant",	variants:[],	traditional:"",},
  {	character:"马",	pinyin:"mǎ",	definition:"horse",	variants:[],	traditional:"馬",},
  {	character:"骨",	pinyin:"gǔ",	definition:"bone",	variants:[],	traditional:"",},
  {	character:"高",	pinyin:"gāo",	definition:"tall",	variants:[],	traditional:"髙",},
  {	character:"髟",	pinyin:"biāo",	definition:"hair",	variants:[],	traditional:"",},
  {	character:"鬥",	pinyin:"dòu",	definition:"fight",	variants:[],	traditional:"",},
  {	character:"鬯",	pinyin:"chàng",	definition:"sacrificial",	variants:[],	traditional:"",},
  {	character:"鬲",	pinyin:"lì",	definition:"cauldron",	variants:[],	traditional:"",},
  {	character:"鬼",	pinyin:"guǐ",	definition:"ghost",	variants:[],	traditional:"",},
  {	character:"鱼",	pinyin:"yú",	definition:"fish",	variants:[],	traditional:"魚",},
  {	character:"鸟",	pinyin:"niǎo",	definition:"bird",	variants:[],	traditional:"鳥",},
  {	character:"卤",	pinyin:"lǔ",	definition:"salt",	variants:[],	traditional:"",},
  {	character:"鹿",	pinyin:"lù",	definition:"deer",	variants:[],	traditional:"",},
  {	character:"麦",	pinyin:"mài",	definition:"wheat",	variants:[],	traditional:"麥",},
  {	character:"麻",	pinyin:"má",	definition:"hemp",	variants:[],	traditional:"",},
  {	character:"黄",	pinyin:"huáng",	definition:"yellow",	variants:[],	traditional:"",},
  {	character:"黍",	pinyin:"shǔ",	definition:"millet",	variants:[],	traditional:"",},
  {	character:"黑",	pinyin:"hēi",	definition:"black",	variants:[],	traditional:"",},
  {	character:"黹",	pinyin:"zhǐ",	definition:"embroidery",	variants:[],	traditional:"",},
  {	character:"黾",	pinyin:"mǐn",	definition:"frog",	variants:[],	traditional:"黽",},
  {	character:"鼎",	pinyin:"dǐng",	definition:"tripod",	variants:[],	traditional:"",},
  {	character:"鼓",	pinyin:"gǔ",	definition:"drum",	variants:[],	traditional:"",},
  {	character:"鼠",	pinyin:"shǔ",	definition:"rat",	variants:[],	traditional:"",}, // 鼡
  {	character:"鼻",	pinyin:"bí",	definition:"nose",	variants:[],	traditional:"",},
  {	character:"齐",	pinyin:"qí",	definition:"even",	variants:["斉"],	traditional:"齊",},
  {	character:"齿",	pinyin:"chǐ",	definition:"tooth",	variants:[],	traditional:"齒",}, // 歯
  {	character:"龙",	pinyin:"lóng",	definition:"dragon",	variants:["竜"],	traditional:"龍",},
  {	character:"龟",	pinyin:"guī",	definition:"turtle",	variants:[],	traditional:"龜",}, // 亀
  {	character:"龠",	pinyin:"yuè",	definition:"flute",	variants:[],	traditional:"",},
];